### ISSUE TITLE
[Loading Cells] Error [deobfuscator.py:3195 process_file(**vars(args))]: 

### ISSUE THREAD

**Issue by diyarbagis** [DissectMalware/XLMMacroDeobfuscator#116]
**Hello, when I try to analyze, I get an error like this.** 

File: /home/kali/Downloads/research-1646684671.xls

Unrecognized file format
Unencrypted xls file

[Loading Cells]
Error [deobfuscator.py:3195 process_file(**vars(args))]: 

**I researched about this error and encountered this : https://github.com/DissectMalware/XLMMacroDeobfuscator/issues/78**

updated xlrd2: pip install -U https://github.com/DissectMalware/xlrd2/archive/master.zip --force

**then, again i tried to analyze but I got the same error.** 

File: /home/kali/Downloads/research-1646684671.xls

Unrecognized file format
Unencrypted xls file

[Loading Cells]
Error [deobfuscator.py:3195 process_file(**vars(args))]: 

**Anyone can help me?**

**Comment by Aphetoros** [comment]
Yup, got the same error as well :( on the exact file (letsdefend) lab

**Comment by bek01** [comment]
Yes, I was trying to solve a challenge on letsdefend, same error. @Aphetoros

**Comment by Hadiqa-khan** [comment]
Same error @Aphetoros

**Comment by DissectMalware** [comment]
Sorry for the late response. 

@diyarbagis @bek01 @Hadiqa-khan @Aphetoros please share the sample or its hash so I can investigate.

**Comment by Anonymous4717** [comment]
i tried to analyze but I got this error.

Unrecognized file format
Unencrypted xls file

[Loading Cells]
Error [deobfuscator.py:3195 process_file(**vars(args))]:

Anyone can help me?
and i set the value to 70 also then also not working

**Comment by Anonymous4717** [comment]
oh now i get it 

first,
edit the formual.py  with sudo nano or whatever find  assert bv >= 80 #### this function needs updating ####
and chnage it **to assert bv >= 70**

**Comment by L4Lu** [comment]
Hello @DissectMalware @Anonymous4717 @diyarbagis 
I'm working on this right now and I get this error:
`python3 -m pip install -U https://github.com/DissectMalware/xlrd2/archive/master.zip --force`
`Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/DissectMalware/xlrd2/archive/master.zip
  Using cached https://github.com/DissectMalware/xlrd2/archive/master.zip
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error`
  
`  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-3ij4azo4/setup.py", line 11, in <module>
          setup(
        File "/home/tsurugi/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          _install_setup_requires(attrs)
        File "/home/tsurugi/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 71, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "/home/tsurugi/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 53, in __init__
          super().__init__(filtered)
        File "/home/tsurugi/.local/lib/python3.10/site-packages/setuptools/dist.py", line 301, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
          ordered = sorted(eps, key=by_group)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1018, in <genexpr>
          eps = itertools.chain.from_iterable(
        File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
          k = key(element)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 943, in _normalized_name
          or super()._normalized_name
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
          return Prepared.normalize(self.name)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize`
  `        return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
        File "/usr/lib/python3.10/re.py", line 209, in sub
          return _compile(pattern, flags).sub(repl, string, count)
      TypeError: expected string or bytes-like object
      [end of output]`
  
`  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed`

`× Encountered error while generating package metadata.
╰─> See above for output.`

`note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`



when i switch to python2
`python2 -m pip install -U https://github.com/DissectMalware/xlrd2/archive/master.zip --force
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/DissectMalware/xlrd2/archive/master.zip
  Using cached https://github.com/DissectMalware/xlrd2/archive/master.zip
Building wheels for collected packages: xlrd2
  Building wheel for xlrd2 (setup.py) ... done
  Created wheel for xlrd2: filename=xlrd2-1.3.4-py2.py3-none-any.whl size=115834 sha256=ebb2385edd5ff75d53a448ae93a8ee741c9ead5a49a8624763556e0962aa9bf2
  Stored in directory: /tmp/pip-ephem-wheel-cache-8Msz6W/wheels/4b/c2/ba/f5501efee71f533947296ea469af8e16f40f57ba09934e29ea
Successfully built xlrd2
Installing collected packages: xlrd2
  Attempting uninstall: xlrd2
    Found existing installation: xlrd2 1.3.4
    Uninstalling xlrd2-1.3.4:
      Successfully uninstalled xlrd2-1.3.4
Successfully installed xlrd2-1.3.4`
but then I get the same error running 
`
xlmdeobfuscator -f research-1646684671.xls
(...)
[Loading Cells]
Error [deobfuscator.py:3195 process_file(**vars(args))]:`

I also switch the assert to be equal 70 but that did not helped.
Can anyone help me?
